### ISSUE TITLE
Ios version incompatible 

### ISSUE THREAD

**Issue by jacklolidk** [abomb4/super-cheat#1]
Please create a version that is compatible with the IOS version of mindustry.

**Comment by abomb4** [comment]
I don't have IOS device, would you provide the crash log? Maybe I can find something in it.

**Comment by abomb4** [comment]
I can't fix this, because the scripts in Mindustry Mod cannot be used in IOS.
Related issue:
https://github.com/Anuken/Mindustry/issues/3775
