### ISSUE TITLE
Update fo erekir 136

### ISSUE THREAD

**Issue by CookiesNew** [abomb4/super-cheat#12]
So erekir is now sort of public and the mod doesnt work with it, is there any way i can you use the mod for erekir?

**Comment by CookiesNew** [comment]
Limks for erekir
PC: https://mindustry.dev/erekir
Android: https://mindustry.dev/erekir/android

**Comment by abomb4** [comment]
try v3.0.0

**Comment by CookiesNew** [comment]
It works! thanks.
