### ISSUE TITLE
I can’t use the mod

### ISSUE THREAD

**Issue by josst28** [abomb4/super-cheat#7]
Hello, I added the mod to my game but, it doesn’t respond. More precisely, for example, when I build something coming from your mod, it doesn’t do anything and I cannot interact with the build... I can’t even unbuild it.

**Comment by abomb4** [comment]
> 
> 
> Hello, I added the mod to my game but, it doesn’t respond. More precisely, for example, when I build something coming from your mod, it doesn’t do anything and I cannot interact with the build... I can’t even unbuild it.

Are you using IOS version of Mindustry? The IOS version cannot using any scripts, so this mod will not working.

**Comment by abomb4** [comment]
It must be IOS version, that version is jailed, no mods that contain scripts available
